# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"

install: pip install -r requirements/dev.txt

script: py.test tests

addons:
  postgresql: "9.3"

env:
  global:
    - SQLALCHEMY_DATABASE_URI=postgres://postgres@localhost/clearstate
